sudo: required
dist: trusty
language: python

addons:
    apt:
        packages:
            - gfortran
            - libblas-dev
            - liblapack-dev
            - samtools

before_cache:   # prevent logs from caching
    - rm -f $HOME/.cache/pip/log/debug.log

cache:
    - ccache
    - pip

install:
    - pip install tox
    # install bedtools
    - wget https://github.com/arq5x/bedtools2/releases/download/v2.27.1/bedtools-2.27.1.tar.gz
    - tar -zxvf bedtools-2.27.1.tar.gz
    - pushd bedtools2 && make && popd
    - export PATH=$PATH:$PWD/bedtools2/bin/
    # install STAR
    - wget https://github.com/alexdobin/STAR/archive/2.6.1a.tar.gz
    - tar -xzf 2.6.1a.tar.gz
    - export PATH=$PATH:$PWD/STAR-2.6.1a/bin/Linux_x86_64/

matrix:
  include:
    - env: TOX_ENV=py35
      python: "3.5"
    - env: TOX_ENV=py36
      python: "3.6"
    - env: TOX_ENV=linters
      python: "3.6"
    - env: TOX_ENV=docs
      python: "3.6"
    - env: TOX_ENV=packaging
      python: "3.6"

script:
  - tox -e $TOX_ENV

after_success:
  - pip install codecov
  - codecov -e TOX_ENV

notifications:
    email: false
